import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print("Addition is : \n",arr1+arr2)
print("Multiplication is : \n",arr1@arr2)
print("Multiplication is : \n",np.matmul(arr1,arr2))
print("Addition is : \n",arr1+arr2)
print(np.min(arr1))
print(np.max(arr1))
print(np.mean(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.argmin(arr1))
print(np.argmax(arr1))
print(np.sqrt(np.std(arr1)))